### PR TITLE
#158560941 Create category's page

### PR DESCRIPTION
**Pull request by chadwalt**
#### What does this PR do?
Adds a category page that the administrator can use to add, edit and delete categories.

#### Description of the task to be completed?
Currently, there is no page in the application where an administrator can create categories from which normal users can subscribe. This pull request adds a category's page where the administrator can create, edit and delete categories.

#### How should this be manually tested?
By logging into the application and navigating to `/category`

#### What are the relevant pivotal tracker stories?
[#158560941](https://www.pivotaltracker.com/story/show/158560941)
#### Screenshots
screen shot 2018-07-18 at 09 52 01
screen shot 2018-07-18 at 09 52 11
screen shot 2018-07-18 at 09 52 19

### CODE REVIEW

**Comment by Maxcutex** [comment]
1. Create Category - is there no way to make the check of role enumerated instead of =='admin'

**Comment by Maxcutex** [comment]
application_helper.rb - no new line at the end?

**Comment by chadwalt** [comment]
@Maxcutex I have addressed all the issues.

**Review by Maxcutex — APPROVED** [review]
done nice job

**Pull request merged**
